name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
        run: sudo apt-get install -y gcc sqlite3 libsqlite3-dev

      # Step 3: Compile main.c
      - name: Compile main.c
        run: |
          gcc main.c -o main.exe -lsqlite3
          if [ $? -eq 0 ]; then echo "main.c compiled successfully"; else exit 1; fi

      # Step 4: Verify main.exe exists
      - name: Verify main.exe exists
        run: |
          if [ -f ./main.exe ]; then echo "main.exe exists"; else echo "main.exe does not exist"; exit 1; fi

      # Step 5: Compile test.c
      - name: Compile test.c
        run: |
          gcc test.c -o test.exe -lsqlite3
          if [ $? -eq 0 ]; then echo "test.c compiled successfully"; else exit 1; fi

      # Step 6: Run the main executable to set up the database
      - name: Setup Database
        run: ./main.exe

      # Step 7: Print database contents for debugging
      - name: Print database contents
        run: |
          sqlite3 test.db "SELECT name FROM sqlite_master WHERE type='table';"
          sqlite3 test.db "PRAGMA table_info(urls);"

      # Step 8: Run the test executable
      - name: Run tests
        run: ./test.exe
